homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 13
  unit_system: metric
  time_zone: !secret homeassistant_time_zone

# Customization of entities
  customize: !include_dir_merge_named customize/

# Enables the frontend
frontend:

# Number of days history is stored in DB
recorder:
  purge_days: 1
  db_url: postgres://@/homeassistant
  exclude:
    domains:
      - group
      - proximity

# Password to log on to Front-End
http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url

# Checks for available updates
updater:

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Discover some devices automatically
#discovery:

###########################################################################################
# includes
sensor: !include include/include_sensor.yaml
automation: !include_dir_merge_list automation/
script: !include include/include_script.yaml
group: !include include/include_group.yaml
zone: !include include/include_zone.yaml
scene: !include include/include_scene.yaml
media_player: !include include/include_media_player.yaml
binary_sensor: !include include/include_binary_sensor.yaml
input_select: !include include/include_input_select.yaml
alert: !include include/include_alert.yaml
input_boolean: !include include/include_input_boolean.yaml
input_slider: !include include/include_input_slider.yaml
panel_iframe: !include include/include_panel_iframe.yaml

###########################################################################################
# mqtt used for presence detection through owntracks
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: !secret mqtt_client_id
  keepalive: 60

###########################################################################################
# zwave
zwave:
  usb_path: !secret zwave_usb_path

###########################################################################################
device_tracker:

# nmap
  - platform: nmap_tracker
    hosts:
      - !secret device_tracker_nmap_tracker_ip1
      - !secret device_tracker_nmap_tracker_ip2
    consider_home: 180
    track_new_devices: no
    interval_seconds: 20

# owntracks
  - platform: owntracks
    max_gps_accuracy: 250
    consider_home: 60

###########################################################################################
proximity:
  home:
    devices:
      - device_tracker.benoitphone_location_benoit
      - device_tracker.jurgenphone_location_jurgen
    tolerance: 100
    unit_of_measurement: km

###########################################################################################
# google calendar events
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

# text-to-speech
tts:
  - platform: google
    cache: true
    cache_dir: tts
    time_memory: 300

###########################################################################################
# ifttt maker channel
ifttt:
  key: !secret ifttt_key

###########################################################################################
# emulated hue for google home
#emulated_hue:
#  type: google_home
#  listen_port: !secret emulated_hue_listen_port
#  host_ip: !secret emulated_hue_host_ip
#  off_maps_to_on_domains:
#    - script
#    - scene
#  expose_by_default: true
#  exposed_domains:
#    - light
#    - switch
#    - scene
#    - script
#    - media_player
#    - group

###########################################################################################
light:
# hue
  - platform: hue
    host: !secret lights_hue_host

# flux
# !!! added entry in hosts file to translate device names into IP addresses !!!
  - platform: flux_led
    devices:
      flux-nightlamp-benoit:
        name: bednightlamp_benoit
        mode: "rgbw"
      flux-nightlamp-jurgen:
        name: bednightlamp_jurgen
        mode: "rgbw"

###########################################################################################
notify:
# telegram
  - name: Telegram
    platform: telegram
    api_key: !secret notify_telegram_api_key
    chat_id: !secret notify_telegram_chat_id

# instaPush
  - name: iphone_benoit
    platform: instapush
    api_key: !secret notify_instapush_iphone_benoit_api_key
    app_secret: !secret notify_instapush_iphone_benoit_app_secret
    event: notification
    tracker: message

  - name: iphone_jurgen
    platform: instapush
    api_key: !secret notify_instapush_iphone_jurgen_api_key
    app_secret: !secret notify_instapush_iphone_jurgen_app_secret
    event: notification
    tracker: message

###########################################################################################
# nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

